[project]
name = "drivers"
version = "0.0.1"
authors = [
    { name="Jason Wilkes", email="notarealdeveloper@gmail.com" },
]
description = "Unix input drivers for Software 2.0"
dependencies = [
    "pytest",
    "Pillow",
    "transformers",
    "pypdf",
    "assure",
    "mmry",
]

[project.urls]
source = "https://github.com/notarealdeveloper/drivers"
download = "https://pypi.org/project/drivers/#files"

[project.scripts]
drivers-pdf   = "drivers.pdf.__main__:main"
drivers-image = "drivers.image.__main__:main"
