[project]
name = "drivers"
version = "0.0.4"
authors = [
    { name="Jason Wilkes", email="notarealdeveloper@gmail.com" },
]
description = "Unix input drivers for Software 2.0"
dependencies = [
    "pytest",
    "requests",
    "bs4",
    "fleep",
    "validators",
    "Pillow",
    "pypdf",
    "transformers",
    "assure",
    "mmry >= 0.0.3",
]

[project.urls]
source = "https://github.com/notarealdeveloper/drivers"
download = "https://pypi.org/project/drivers/#files"

[project.scripts]
input       = "drivers.__main__:main"
input-pdf   = "drivers.pdf:main"
input-image = "drivers.image:main"
input-html  = "drivers.html:main"
pdf         = "drivers.pdf:main"
image       = "drivers.image:main"
html        = "drivers.html:main"
